use_frameworks!

target 'ECKit-Utils_Example' do
  pod 'ECKit-Utils', :path => '../'

  target 'ECKit-Utils_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
